export const SET_CURRENT_USER_LOCATION = 'SET_CURRENT_USER_LOCATION';
export const SET_CURRENT_USER_MARKER = 'SET_CURRENT_USER_MARKER';
export const SET_NEARBY_GYM_INFO = 'SET_NEARBY_PLACE_INFO';
export const SET_CARD_ARRAY = 'SET_CARD_ARRAY';
export const SET_MARKERS = 'SET_MARKERS';

export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_TOKEN_STATUS = 'SET_USER_TOKEN_STATUS';

export const SET_DASHBOARD_PANE = 'SET_DASHBOARD_PANE';

export const SHOW_MODAL_CHOOSE_GYM = 'SHOW_MODAL_CHOOSE_GYM';
export const SHOW_MODAL_CONFIRM_GYM = 'SHOW_MODAL_CONFIRM_GYM';
export const SET_MODAL_GYM_DATA = 'SET_MODAL_GYM_DATA';
export const NEW_GYM_ADDED = 'NEW_GYM_ADDED';

export const SHOW_MODAL_CHOOSE_LIFT = 'SHOW_MODAL_CHOOSE_LIFT';
export const SHOW_MODAL_CONFIRM_LIFT = 'SHOW_MODAL_CONFIRM_LIFT';
export const SET_MODAL_LIFT_DATA = 'SET_MODAL_LIFT_DATA';
export const NEW_PR_ADDED = 'NEW_PR_ADDED';

export const SET_GYM_PAGE_INFO = 'SET_GYM_PAGE_INFO';
export const SET_GYM_PAGE_ID = 'SET_GYM_PAGE_ID';
export const SET_CURRENT_NAV_CARD = 'SET_CURRENT_NAV_CARD';

export const SET_SPORT_MEMBERSHIP_TABLE = 'SET_SPORT_MEMBERSHIP_TABLE'
export const SET_MEMBERSHIP_DATA = 'SET_MEMBERSHIP_DATA' 
